keiba/urls.py
from django.urls import path

from . import views

app_name = "predict"

urlpatterns = [
    path('', views.predict, name='prediction_page'),
    path('predict/', views.predict_chances, name='submit_prediction'),
    path('results/', views.view_results, name='results'),
]

keiba_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("keiba.urls"))
]

keiba/models.py
from django.db import models

class PredResults(models.Model):

    frame_number = models.FloatField()
    horse_number = models.FloatField()
    horse_weight = models.FloatField()
    distance = models.FloatField()
    rank = models.FloatField()

    def __str__(self):
        return self.rank

keiba/views.py
from django.shortcuts import render
from django.http import JsonResponse
import pandas as pd
from .models import PredResults

def predict(request):
    return render(request, 'predict.html')

def predict_chances(request):

    if request.POST.get('action') == 'post':

        # Receive data from client
        frame_number = float(request.POST.get('frame_number'))
        horse_number = float(request.POST.get('horse_number'))
        horse_weight = float(request.POST.get('horse_weight'))
        distance = float(request.POST.get('distance'))

        # Unpickle model
        model = pd.read_pickle('./keiba_model/model.pickle')
        # Make prediction
        result = model.predict([[frame_number, horse_number, horse_weight, distance]])

        rank = result[0]

        PredResults.objects.create(frame_number=frame_number, horse_number=horse_number, horse_weight=horse_weight,
                                   distance=distance, rank=rank)

        return JsonResponse({'result': rank, 'frame_number': frame_number,
                             'horse_number': horse_number, 'horse_weight': horse_weight, 'distance': distance},
                            safe=False)


def view_results(request):
    # Submit prediction and show all
    data = {"dataset": PredResults.objects.all()}
    return render(request, "results.html", data)

keiba/templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>KEIBA</title>
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">DB</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

keiba/templates/predict.html
{% extends "base.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Keiba Prediction *WAIT 3SEC!!*</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Prediction Input:</h5>
                <div>frame_number: <span id="sl"></span></div>
                <div>horse_number: <span id="sw"></span></div>
                <div>horse_weight: <span id="pl"></span></div>
                <div>distance: <span id="pw"></span></div>
                <h5 class="pt-3">Prediction rank:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h1>Keiba Prediction</h1>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="frame_number">frame_number</label>
                    <input type="number" step="1" class="form-control" id="frame_number" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="horse_number">horse_number</label>
                    <input type="number" step="1" class="form-control" id="horse_number" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="horse_weight">horse_weight</label>
                    <input type="number" step="1" class="form-control" id="horse_weight" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="distance">distance</label>
                    <input type="number" step="1" class="form-control" id="distance" placeholder="" required>
                </div>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:submit_prediction" %}',
            data:{
                frame_number:$('#frame_number').val(),
                horse_number:$('#horse_number').val(),
                horse_weight:$('#horse_weight').val(),
                distance:$('#distance').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("sl").innerHTML = json['frame_number']
                document.getElementById("sw").innerHTML = json['horse_number']
                document.getElementById("pl").innerHTML = json['horse_weight']
                document.getElementById("pw").innerHTML = json['distance']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>

{% endblock %}

keiba/templates/results.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1>Prediction Results</h1>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">frame_number</th>
                <th scope="col">horse_number</th>
                <th scope="col">horse_weight</th>
                <th scope="col">distance</th>
                <th scope="col">Prediction</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.frame_number }}</td>
                    <td>{{ data.horse_number }}</td>
                    <td>{{ data.horse_weight }}</td>
                    <td>{{ data.distance }}</td>
                    <td>{{ data.rank }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}